
package com.inssjp.mywebservice.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebServicePortType", targetNamespace = "http://business.mywebservice.inssjp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWebServicePortType {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMedicamentosFraccion", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentosFraccion")
    @ResponseWrapper(localName = "sendMedicamentosFraccionResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentosFraccionResponse")
    public WebServiceResult sendMedicamentosFraccion(
        @WebParam(name = "arg0", targetNamespace = "")
        List<MedicamentosDTOFraccion> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendCancelacTransacc", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendCancelacTransacc")
    @ResponseWrapper(localName = "sendCancelacTransaccResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendCancelacTransaccResponse")
    public WebServiceResult sendCancelacTransacc(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceConfirmResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendConfirmaTransacc", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendConfirmaTransacc")
    @ResponseWrapper(localName = "sendConfirmaTransaccResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendConfirmaTransaccResponse")
    public WebServiceConfirmResult sendConfirmaTransacc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<ConfirmacionTransaccionDTO> arg2);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg17
     * @param arg2
     * @param arg18
     * @param arg5
     * @param arg19
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg16
     * @param arg20
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns com.inssjp.mywebservice.business.TransaccionesNoConfirmadasWSResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaccionesNoConfirmadas", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetTransaccionesNoConfirmadas")
    @ResponseWrapper(localName = "getTransaccionesNoConfirmadasResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetTransaccionesNoConfirmadasResponse")
    public TransaccionesNoConfirmadasWSResult getTransaccionesNoConfirmadas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        Long arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        Long arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        Long arg20);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendAlertaTransacc", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendAlertaTransacc")
    @ResponseWrapper(localName = "sendAlertaTransaccResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendAlertaTransaccResponse")
    public WebServiceResult sendAlertaTransacc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Long> arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMedicamentos", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentos")
    @ResponseWrapper(localName = "sendMedicamentosResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentosResponse")
    public WebServiceResult sendMedicamentos(
        @WebParam(name = "arg0", targetNamespace = "")
        List<MedicamentosDTO> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns com.inssjp.mywebservice.business.ConsultaStockWSResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultaStock", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetConsultaStock")
    @ResponseWrapper(localName = "getConsultaStockResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetConsultaStockResponse")
    public ConsultaStockWSResult getConsultaStock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Long arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        Long arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Long arg10);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns com.inssjp.mywebservice.business.TransaccionesNoConfirmadasWSResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEnviosPropiosAlertados", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetEnviosPropiosAlertados")
    @ResponseWrapper(localName = "getEnviosPropiosAlertadosResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetEnviosPropiosAlertadosResponse")
    public TransaccionesNoConfirmadasWSResult getEnviosPropiosAlertados(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        Long arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        Long arg15);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendCancelacTransaccParcial", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendCancelacTransaccParcial")
    @ResponseWrapper(localName = "sendCancelacTransaccParcialResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendCancelacTransaccParcialResponse")
    public WebServiceResult sendCancelacTransaccParcial(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns com.inssjp.mywebservice.business.CatalogoGTINResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatalogoElectronicoByGTIN", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetCatalogoElectronicoByGTIN")
    @ResponseWrapper(localName = "getCatalogoElectronicoByGTINResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetCatalogoElectronicoByGTINResponse")
    public CatalogoGTINResult getCatalogoElectronicoByGTIN(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg17
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg16
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns com.inssjp.mywebservice.business.TransaccionesWSResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaccionesWS", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetTransaccionesWS")
    @ResponseWrapper(localName = "getTransaccionesWSResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetTransaccionesWSResponse")
    public TransaccionesWSResult getTransaccionesWS(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        Long arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        Long arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        Long arg17);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns com.inssjp.mywebservice.business.CatalogoGLNResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatalogoElectronicoByGLN", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetCatalogoElectronicoByGLN")
    @ResponseWrapper(localName = "getCatalogoElectronicoByGLNResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetCatalogoElectronicoByGLNResponse")
    public CatalogoGLNResult getCatalogoElectronicoByGLN(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Long arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Long arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        Long arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendAsignarNroAutorizacion", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendAsignarNroAutorizacion")
    @ResponseWrapper(localName = "sendAsignarNroAutorizacionResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendAsignarNroAutorizacionResponse")
    public WebServiceResult sendAsignarNroAutorizacion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.ConsultaNumeroAutorizacionDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConsultaNumeroAutorizacion", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetConsultaNumeroAutorizacion")
    @ResponseWrapper(localName = "getConsultaNumeroAutorizacionResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.GetConsultaNumeroAutorizacionResponse")
    public ConsultaNumeroAutorizacionDTO getConsultaNumeroAutorizacion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.inssjp.mywebservice.business.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMedicamentosDHSerie", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentosDHSerie")
    @ResponseWrapper(localName = "sendMedicamentosDHSerieResponse", targetNamespace = "http://business.mywebservice.inssjp.com/", className = "com.inssjp.mywebservice.business.SendMedicamentosDHSerieResponse")
    public WebServiceResult sendMedicamentosDHSerie(
        @WebParam(name = "arg0", targetNamespace = "")
        List<MedicamentosDTODHSerie> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
