
package com.inssjp.mywebservice.business;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IWebService", targetNamespace = "http://business.mywebservice.inssjp.com/", wsdlLocation = "https://trazabilidad.pami.org.ar:9050/trazamed.WebService?wsdl")
public class IWebService
    extends Service
{

    private final static URL IWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException IWEBSERVICE_EXCEPTION;
    private final static QName IWEBSERVICE_QNAME = new QName("http://business.mywebservice.inssjp.com/", "IWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new File("trazamed.WebService_wsdl.wsdl").toURL();
            //url = new URL("https://trazabilidad.pami.org.ar:9050/trazamed.WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IWEBSERVICE_WSDL_LOCATION = url;
        IWEBSERVICE_EXCEPTION = e;
    }

    public IWebService() {
        super(__getWsdlLocation(), IWEBSERVICE_QNAME);
    }

    public IWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IWEBSERVICE_QNAME, features);
    }

    public IWebService(URL wsdlLocation) {
        super(wsdlLocation, IWEBSERVICE_QNAME);
    }

    public IWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IWEBSERVICE_QNAME, features);
    }

    public IWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWebServicePortType
     */
    @WebEndpoint(name = "IWebServicePort")
    public IWebServicePortType getIWebServicePort() {
        return super.getPort(new QName("http://business.mywebservice.inssjp.com/", "IWebServicePort"), IWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebServicePortType
     */
    @WebEndpoint(name = "IWebServicePort")
    public IWebServicePortType getIWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.mywebservice.inssjp.com/", "IWebServicePort"), IWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IWEBSERVICE_EXCEPTION!= null) {
            throw IWEBSERVICE_EXCEPTION;
        }
        return IWEBSERVICE_WSDL_LOCATION;
    }

}
